In [6]:
import numpy as np
import pandas as pd

In [9]:
zeros_arr = np.zeros((3, 3))
df = pd.DataFrame(zeros_arr)
print(df)

     0    1    2
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0


In [ ]:
np.zeros((3,3))
np.where
np.select

In [13]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.arange(0,20,2)

for i in range(0,20,2):
    print (i) 

0
2
4
6
8
10
12
14
16
18


In [38]:
#1:
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
#2:
arr2 = np.zeros((3,3))
##3:
arr3 = np.array((2,4), dtype=np.int32)
#4:
arr4 = np.arange(16)
reshaped_arr4 = arr4.reshape((4,4))
#5:
arr5 = np.linspace(0, 5, num = 10)
#6:
even_array = np.arange(2, 11, 2)
#7:
arr7 = np.eye(5)
#8:
arr8 = np.random.randint(1, 100)
#9:
arr9 = np.full((2,3,2), 7)

#10
arr10 = np.logspace(2, 5, num =5, base = 10)
##Array Manipulation:
#11:
arr12 = np.arange(12)
reshaped = arr12.reshape(3,4)
##12:
arr11 = np.arange(2,3)
flatten_aray = np.ravel(arr11)
#13:
arr13 = np.arange(16)
re_shaped = arr13.reshape((4,4))
secon_row = arr13[1:]
#14:
arr14 = np.array([[3,3], [3,3], [3,3]], dtype = np.int32)
arr14[[0,2]] = arr14[[2,0]]

##15:
arr15 = np.array([1, 2, 3, 4, 5, 6, 7 ,8, 9])
arr15[arr15 > 5] = 0
#16:
arr16 = np.ones((5,5), dtype = np.int32)
arr16[0, :]  = 0
arr16[-1, :] = 0
arr16[:,0] = 0
arr16[:,-1] = 0

#17:
arr17 = np.array([[1,2,3,4],
                  [5,4,6,3],
                  [2,4,5,1],
                  [11,43,53,12]])

diagnol_elements = np.diag(arr17)

#18:
arr18 = np.array([[2,3,4,5],
                 [34,4,53, 5],
                  [12, 13, 15, 16]])
reversed_col = np.fliplr(arr18)
                  
#19:
arr19 = np.array([[12, 13, 14], [1, 2, 3], [6, 6, 7]])
arr19_transposed  = arr19.T
stacked = np.vstack((arr19, arr19_transposed))

##20:
arr20 = np.array([[1,2,3,4,5,6],
                 [12,13,14,11,15,16],
                 [21,22,23,24,25,26],
                 [31,32,33,34,35,36],
                 [41,42,43,44,45,46],
                 [51,52,53,54,55,56]])

arr_subarray = np.vsplit(arr20, 3)
                 

In [58]:
print(even_array)

[ 2  4  6  8 10]


# Array Operations:


In [45]:
#21:
array1  = np.array([[1,2,3,4,5]])
array2 = np.array([[11,12,13,14,15]])
sum_array = np.add(array1, array2)

In [47]:
#22:
arr2x3 = np.array([[2,3,4],
                   [12,22,33]])
scaler_value = 4
multiplied = arr2x3 * scaler_value

In [49]:
#23:
arr23 = np.array([[1,2,3,4]])
squared = arr23 ** 2

In [53]:
#24:
arr1 = np.array([[2,2],
                [4,6]])
arr2 = np.array([[33,27],
                 [3,7]])

division = np.divide(arr1, arr2)

In [61]:
##25:
arr25 = np.linspace(0, np.pi, num=5)
sin_arr = np.sin(arr25)


In [71]:
#26:
arr = np.array([[1, 2, 3]])
              
arr2 = np.array([[1,2,3],
                 [4,5,6]])

add_array = arr + arr2

In [65]:
arr

array([[1],
       [2],
       [3]])

In [77]:
#27:
array = np.random.randint(1, 11, size = (3, 3))
array2 = np.random.randint(11, 22, size = (3, 3))

multiplied = np.multiply(array, array2)

In [79]:
#28: 
arr28 = np.array([[2,3],
                  [4,5]])
raised_cube = np.power(arr28, 3)

In [83]:
#29: 
arr29 = np.array([[1,2,3,4],
                  [2,4,6,8],
                  [10,12,14,16],
                  [20,22,24,26]])
array_mean = np.mean(arr29)

subtraction = arr29 - array_mean

In [85]:
subtraction

array([[-9.875, -8.875, -7.875, -6.875],
       [-8.875, -6.875, -4.875, -2.875],
       [-0.875,  1.125,  3.125,  5.125],
       [ 9.125, 11.125, 13.125, 15.125]])

In [105]:
#30:
arr = np.array([[1], [2], [3]])
arr1 = np.array([[11, 22, 33]])

multiplied = arr * arr1

In [107]:
multiplied

array([[11, 22, 33],
       [22, 44, 66],
       [33, 66, 99]])

# statistical functions

In [116]:
##31:
random_integers = np.random.randint(10, 100, 10)

meaned_value = np.mean(random_integers)

In [122]:
#32:
arr32 = np.array([[3,2,4],
                  [21,34,54],
                  [11,2,32]])
maximum_value = np.max(arr32)

In [124]:
#33:
arr33 = np.array([[23,21,33,45],
                  [12,56,76,31]])
sumed_value = np.sum(arr33)

In [126]:
##34:
arr34 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
arr_standard_deviation = np.std(arr34)


In [128]:
##35:
arr35 = np.array([[1,2,3,4],
                  [11,12,13,14],
                  [21,22,23,24],
                  [31,32,34,35]])

minimum_value = np.min(arr35, axis = 1)
                

In [130]:
##36:
arr36 = np.array([ [1, 2, 3, 4, 5]])
median_array = np.median(arr36)

In [138]:
##37:
arr37 = np.random.randint(0, 10, size=(5,5))
mean_colwise = np.mean(arr37, axis=0)

In [140]:
##38:
arr38 = np.array([2,12,np.nan, np.nan, 16, 54, np.nan])
mean_value = np.nanmean(arr38)
arr38[np.isnan(arr38)] = mean_value

In [142]:
##39:


In [144]:
##40:
arr40 = np.array([1, 2, 3, 4, 5, 6])
cumulative_sum = np.cumsum(arr40)

# Linear Algebra:

In [149]:
#41:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
dot_product = np.dot(array_1, array_2)

In [151]:
#42:
arr41 = np.array([[2,3,4],
                  [3,6,7]])

arr41_tanspose = np.transpose(arr41)

In [159]:
##43:
arr_1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

matmul_prod = np.matmul(arr_1, arr2)
#44:
determinant_arr42 = np.linalg.det(arr_1)

In [161]:
#45:
array44 = np.array([[1,2,3],
                    [4,3,5],
                    [11,14,17]])
traced_array = np.trace(array44)

In [165]:
#46:
arr45 = np.array([[5, 6],
                 [7, 8]])
inverse_arr45 = np.linalg.inv(arr45)

In [167]:
#47:
arr46 = np.array([[1,2,3],
                    [4,3,5],
                    [11,14,17]])
arr_46 = np.array([1, 3, 5])
solved_eq = np.linalg.solve(arr46, arr_46)

In [169]:
#48:
arr47 = np.array([[5, 6],
                 [7, 8]])
x = np.linalg.eigvals

In [171]:
#49:
arr48 = np.array([[2, 3, 4], [1, 2, 3], [6, 7, 8]]) #3x2
arr_48 = np.array([[4, 5, 6], [1, 2, 4]]) #2x3

multiplication = np.matmul(arr48, arr_48)



In [173]:
#50:
arr50 = np.array([1, 2, 3, 4, 5])
normalize_arr50 = np.linalg.norm(arr50)
normalized_arr = arr50/normalize_arr50
